# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# IP: ip/Divideru/Divideru.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Divideru || ORIG_REF_NAME==Divideru} -quiet] -quiet

# IP: ip/Dividers/Dividers.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Dividers || ORIG_REF_NAME==Dividers} -quiet] -quiet

# IP: ip/CLK_PLL/CLK_PLL.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CLK_PLL || ORIG_REF_NAME==CLK_PLL} -quiet] -quiet
