# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mithi/RISV/RISV.srcs/sources_1/ip/CLK_SEG/CLK_SEG.xci
# IP: The module: 'CLK_SEG' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/CLK_SEG/CLK_SEG_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_SEG'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/CLK_SEG/CLK_SEG.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_SEG'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/CLK_SEG/CLK_SEG_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_SEG'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mithi/RISV/RISV.srcs/sources_1/ip/CLK_SEG/CLK_SEG.xci
# IP: The module: 'CLK_SEG' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/CLK_SEG/CLK_SEG_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_SEG'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/CLK_SEG/CLK_SEG.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_SEG'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/CLK_SEG/CLK_SEG_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_SEG'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
