# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mithi/RISV/RISV.srcs/sources_1/ip/unsigned_mulh/unsigned_mulh.xci
# IP: The module: 'unsigned_mulh' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/unsigned_mulh/unsigned_mulh_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_mulh'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/mithi/RISV/RISV.srcs/sources_1/ip/unsigned_mulh/unsigned_mulh.xci
# IP: The module: 'unsigned_mulh' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/unsigned_mulh/unsigned_mulh_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_mulh'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
