/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 08/06/2019 04:02:28
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_SYSCLKFreq_VALUE                     32000000
#define MX_HCLKFreq_Value                       32000000
#define MX_FCLKCortexFreq_Value                 32000000
#define MX_CortexFreq_Value                     32000000
#define MX_AHBFreq_Value                        32000000
#define MX_APB1Freq_Value                       32000000
#define MX_APB2Freq_Value                       32000000
#define MX_APB1TimFreq_Value                    32000000
#define MX_APB2TimFreq_Value                    32000000
#define MX_PWRFreq_Value                        32000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        64000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    32000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_ADCx_IN9_Pin                         PA4
#define MX_ADCx_IN9_GPIOx                       GPIOA
#define MX_ADCx_IN9_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN9_GPIO_Pin                    GPIO_PIN_4
#define MX_ADCx_IN9_GPIO_Mode                   GPIO_MODE_ANALOG_ADC_CONTROL

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PA9 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PA9
#define MX_I2C1_SCL_GPIOx                       GPIOA
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PA10 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PA10
#define MX_I2C1_SDA_GPIOx                       GPIOA
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_10
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 (JTMS-SWDIO) */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13_JTMS_SWDIO

/* Pin PA14 (JTCK-SWCLK) */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14_JTCK_SWCLK

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2

/* Pin PA15 (JTDI) */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Pin                        PA15_JTDI
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_15
#define MX_USART2_RX_GPIO_AF                    GPIO_AF3_USART2

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB3 (JTDO-TRACESWO) */
#define MX_PB3_JTDO_TRACESWO_GPIO_Speed         GPIO_SPEED_FREQ_LOW
#define MX_PB3_JTDO_TRACESWO_Pin                PB3_JTDO_TRACESWO
#define MX_PB3_JTDO_TRACESWO_GPIOx              GPIOB
#define MX_PB3_JTDO_TRACESWO_PinState           GPIO_PIN_RESET
#define MX_PB3_JTDO_TRACESWO_GPIO_PuPd          GPIO_NOPULL
#define MX_PB3_JTDO_TRACESWO_GPIO_Pin           GPIO_PIN_3
#define MX_PB3_JTDO_TRACESWO_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

