/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package picsaver;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mithilesh
 */
public class Main extends javax.swing.JFrame {

    final String res = "Resolution: ";
    /**
     * Creates new form Main
     */
    list picArray = new list();
    public Main() {
        initComponents();
        fileCho.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "tif"));
        jPanel1.setBorder(BorderFactory.createTitledBorder("Picture"));
        jPanel2.setBorder(BorderFactory.createLineBorder(new Color(221,221,221)));
        fileCho.setMultiSelectionEnabled(true);
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        picture.HEIGHT = (int) screenSize.getHeight()/2;
        picture.WIDTH = (int) screenSize.getWidth()/2;
        System.out.println(picture.WIDTH+"x"+picture.HEIGHT);
        screenSize = null;  
        
        jPanel1.setSize(picture.WIDTH, picture.HEIGHT);
        System.out.println(jPanel1.getSize().toString());
        dialog.setLocation(200, 200);
        dialog.setSize((int) fileCho.getSize().getWidth()+100, (int) fileCho.getSize().getHeight()+100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        fileCho = new javax.swing.JFileChooser();
        dialogBar = new javax.swing.JDialog();
        progressBar = new javax.swing.JProgressBar();
        barLabel = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        dialogErr = new javax.swing.JDialog();
        errorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        picList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        picName = new javax.swing.JTextField();
        convertBtn = new javax.swing.JButton();
        resLabel = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        choPic = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fileCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fileCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogBar.setSize(new java.awt.Dimension(100, 100));

        barLabel.setText("Loading Picture(s)");

        javax.swing.GroupLayout dialogBarLayout = new javax.swing.GroupLayout(dialogBar.getContentPane());
        dialogBar.getContentPane().setLayout(dialogBarLayout);
        dialogBarLayout.setHorizontalGroup(
            dialogBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogBarLayout.setVerticalGroup(
            dialogBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        errorLabel.setText("jLabel2");

        javax.swing.GroupLayout dialogErrLayout = new javax.swing.GroupLayout(dialogErr.getContentPane());
        dialogErr.getContentPane().setLayout(dialogErrLayout);
        dialogErrLayout.setHorizontalGroup(
            dialogErrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogErrLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        dialogErrLayout.setVerticalGroup(
            dialogErrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogErrLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(100, 100));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(picLabel, java.awt.BorderLayout.PAGE_START);

        picList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                picListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(picList);

        jLabel1.setText("Selected Picture:");

        picName.setEditable(false);
        picName.setBackground(new java.awt.Color(255, 255, 255));

        convertBtn.setText("Convert Picture(s)");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        resLabel.setText("Resolution:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resLabel))
                    .addComponent(convertBtn))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(picName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertBtn)
                .addContainerGap())
        );

        file.setText("File");

        choPic.setText("Choose Picture(s)");
        choPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choPicActionPerformed(evt);
            }
        });
        file.add(choPic);

        menu.add(file);

        edit.setText("Edit");
        menu.add(edit);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choPicActionPerformed
        boolean add = false;
        errorLabel.setText("Error Loading:\n");
        if(fileCho.showOpenDialog(Main.this) == JFileChooser.APPROVE_OPTION){
            File pic[] = fileCho.getSelectedFiles();
            for (int i = 0; i < pic.length; i++) {
                if(picArray.find(pic[i].getName().substring(0, pic[i].getName().lastIndexOf("."))) == -1){
                    picArray.add(pic[i]);
                    add = true;
                }
                else errorLabel.setText(errorLabel.getText()+pic[i].getName()+"\n");
            }
        }
        if(add){
            update();
            picName.setText(picArray.getEnd().getName());
            resLabel.setText(res+picArray.getEnd().getRes());
            picLabel.setIcon(picArray.getEnd().getIcon());
            picName.setCaretPosition(0);
            picList.setSelectedIndex(picList.getModel().getSize()-1);
        }
        //dialogErr.setVisible(true);
    }//GEN-LAST:event_choPicActionPerformed

    private void picListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_picListValueChanged
        try{
            String name = picList.getSelectedValue();
            int index = picArray.find(name);
            picName.setText(picArray.get(index).getName());
            resLabel.setText(res+picArray.get(index).getRes());
            picLabel.setIcon(picArray.get(index).getIcon());
            picName.setCaretPosition(0);
        }
        catch(ArrayIndexOutOfBoundsException e){
            
        }
    }//GEN-LAST:event_picListValueChanged

    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        
    }//GEN-LAST:event_convertBtnActionPerformed
    
    private void update(){
        String list[] = new String[picArray.size()];
        for (int i = 0; i < picArray.size(); i++) {
            list[i] = picArray.get(i).getName();
        }
        picList.setListData(list);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem choPic;
    private javax.swing.JButton convertBtn;
    private javax.swing.JDialog dialog;
    private javax.swing.JDialog dialogBar;
    private javax.swing.JDialog dialogErr;
    private javax.swing.JMenu edit;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JMenu file;
    private javax.swing.JFileChooser fileCho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel picLabel;
    private javax.swing.JList<String> picList;
    private javax.swing.JTextField picName;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel resLabel;
    // End of variables declaration//GEN-END:variables
}